### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by sedrubal** [MarcDufresne/BetterWeather#30]
There often appears an api error message. Sometimes it goes away on refreshing but sometimes it won't disappear...

**Comment by improti** [comment]
I only get the error and never got any weather info, yet.

**Comment by ItchyDemon** [comment]
I get this consistently using OpenWeatherMap, but I never see this with Yahoo Weather. Other apps that use OpenWeatherMap never show this issue and always appear successful updating their weather info, so I doubt it's OpenWeatherMap's service causing this issue.

**Comment by ChgoChad** [comment]
I am having the same issue.. I just installed the plug-in and in both Yahoo and OpenWeatherMap I get the API error message. 

I do know that Yahoo changed their API a few days ago and updated the way users authenticate to get the information. This could likely be the culprit...

**Comment by MarcDufresne** [comment]
So, I finally had time to work on this app, I just pushed an update which fixes OpenWeatherMap and removes Yahoo Weather. You guys can try again with that version. Thanks!

**Comment by mmirg** [comment]
I see this error with both Yahoo! Weather and OpenWeather Map when using BetterWeather 4.1 with Android 7.0.

**Comment by MarcDufresne** [comment]
@mmirg what's happening now is another issue, see #33
