### ISSUE TITLE
Make API key user-writeable

### ISSUE THREAD

**Issue by krt16s** [MarcDufresne/BetterWeather#31]
I know this is a rather strange request, but would it be possible to allow the user to provide a new api key (not view the old one)? API keys are essentially a a threat to free software, because you cannot run/build without it, thus are required to enter a legal contract which in most cases prohibits the publication of API keys. From my perspective API keys shouldn't be part of the app, but should be user-entered.. well..like personal accounts without personal information.

**Comment by MarcDufresne** [comment]
I already tried this idea when I implemented the Forecast API but I was contacted by them shortly after to ask me to remove the ability to input your own API key as it was against their terms of service, which in turn made me remove their API entirely as it is paid and I make no money with my app. I don't want to risk another breach of terms with another provider. So sadly I won't be able to add this.

You can however fork the repo and insert your own key in the code if you are familiar with Java and Android. You'll then be able to run your own version of the app.
